import { auth, db } from "hatchable";

export const access = "user";
export const methods = ["GET", "POST"];

async function currentUser(req) { return req.user || await auth.getUser(req); }
async function getOrCreateMarket(userId, name = "My Market") { const existing = await db.query(`SELECT id, name, city, state FROM markets WHERE owner_user_id = $1 AND active = true ORDER BY created_at ASC LIMIT 1`, [userId]); if (existing.rows[0]) return existing.rows[0]; const created = await db.query(`INSERT INTO markets (owner_user_id, name) VALUES ($1, $2) RETURNING id, name, city, state`, [userId, name]); return created.rows[0]; }
function validWasteType(value) { return ['organic','plastic','paper','glass','metal','textile','general','special'].includes(value); }
function validStatus(value) { return ['assigned','arrived','collected','in_transit','delivered','cancelled'].includes(value); }

export default async function (req, res) {
  const user = await currentUser(req); if (!user) return res.status(401).json({ error: "Not signed in. Please sign in again." }); const userId = String(user.id);
  if (req.method === "GET") {
    const market = await getOrCreateMarket(userId);
    const [zones, points, truckers, facilities, jobs] = await Promise.all([
      db.query(`SELECT id, name FROM market_zones WHERE market_id = $1 ORDER BY name`, [market.id]),
      db.query(`SELECT id, name, code, zone_id FROM collection_points WHERE market_id = $1 AND active = true ORDER BY name`, [market.id]),
      db.query(`SELECT id, company_name, driver_name, phone, vehicle_registration, truck_capacity_kg, waste_types, reliability_score FROM truckers WHERE owner_user_id = $1 AND active = true ORDER BY company_name`, [userId]),
      db.query(`SELECT id, name, facility_type, address, accepted_waste_types FROM disposal_facilities WHERE owner_user_id = $1 AND active = true ORDER BY name`, [userId]),
      db.query(`SELECT j.id, j.waste_type, j.estimated_weight_kg, j.collected_weight_kg, j.collection_fee, j.status, j.requested_at, j.collected_at, j.delivered_at, cp.name AS collection_point_name, cp.code AS collection_point_code, t.company_name AS trucker_company, t.vehicle_registration, f.name AS facility_name FROM waste_jobs j LEFT JOIN collection_points cp ON cp.id = j.collection_point_id LEFT JOIN truckers t ON t.id = j.trucker_id LEFT JOIN disposal_facilities f ON f.id = j.facility_id WHERE j.market_id = $1 ORDER BY j.requested_at DESC LIMIT 30`, [market.id])
    ]);
    const summary = await db.query(`SELECT COUNT(*) FILTER (WHERE status NOT IN ('delivered','cancelled')) AS open_jobs, COUNT(*) FILTER (WHERE status = 'delivered') AS completed_jobs, COALESCE(SUM(CASE WHEN status != 'cancelled' THEN estimated_weight_kg ELSE 0 END), 0) AS estimated_kg, COALESCE(SUM(CASE WHEN status = 'delivered' THEN collected_weight_kg ELSE 0 END), 0) AS delivered_kg FROM waste_jobs WHERE market_id = $1`, [market.id]);
    return res.json({ market, zones: zones.rows, collection_points: points.rows, truckers: truckers.rows, facilities: facilities.rows, jobs: jobs.rows, summary: summary.rows[0] });
  }
  const body = req.body || {}; const action = body.action;
  try {
    if (action === 'setup_market') { const name = String(body.name || '').trim(); if (!name || name.length > 100) return res.status(400).json({ error: 'Enter a market name under 100 characters.' }); const market = await getOrCreateMarket(userId, name); const updated = await db.query(`UPDATE markets SET name = $1, city = NULLIF($2, ''), state = NULLIF($3, '') WHERE id = $4 AND owner_user_id = $5 RETURNING id, name, city, state`, [name, String(body.city || '').trim(), String(body.state || '').trim(), market.id, userId]); return res.json({ ok: true, market: updated.rows[0] }); }
    const market = await getOrCreateMarket(userId);
    if (action === 'add_zone') { const name = String(body.name || '').trim(); if (!name || name.length > 100) return res.status(400).json({ error: 'Enter a zone name.' }); const r = await db.query(`INSERT INTO market_zones (market_id, name) VALUES ($1, $2) RETURNING id, name`, [market.id, name]); return res.status(201).json({ ok: true, zone: r.rows[0] }); }
    if (action === 'add_point') { const name = String(body.name || '').trim(); const zoneId = body.zone_id || null; if (!name) return res.status(400).json({ error: 'Enter a collection point name.' }); if (zoneId) { const z = await db.query(`SELECT id FROM market_zones WHERE id = $1 AND market_id = $2`, [zoneId, market.id]); if (!z.rows[0]) return res.status(400).json({ error: 'That zone does not belong to this market.' }); } const code = `MKT-${market.id.slice(0,8).toUpperCase()}-${Date.now().toString(36).toUpperCase()}`; const r = await db.query(`INSERT INTO collection_points (market_id, zone_id, name, code) VALUES ($1, $2, $3, $4) RETURNING id, name, code, zone_id`, [market.id, zoneId, name, code]); return res.status(201).json({ ok: true, collection_point: r.rows[0] }); }
    if (action === 'add_trucker') { const company = String(body.company_name || '').trim(); const driver = String(body.driver_name || '').trim(); const registration = String(body.vehicle_registration || '').trim(); const capacity = Number(body.truck_capacity_kg); if (!company || !driver || !registration || !Number.isFinite(capacity) || capacity <= 0) return res.status(400).json({ error: 'Company, driver, vehicle registration and truck capacity are required.' }); const wasteTypes = Array.isArray(body.waste_types) && body.waste_types.length ? body.waste_types.filter(validWasteType) : ['general']; const r = await db.query(`INSERT INTO truckers (owner_user_id, company_name, driver_name, phone, vehicle_registration, truck_capacity_kg, waste_types) VALUES ($1, $2, $3, NULLIF($4, ''), $5, $6, $7) RETURNING id, company_name, driver_name, phone, vehicle_registration, truck_capacity_kg, waste_types, reliability_score`, [userId, company, driver, String(body.phone || '').trim(), registration, capacity, wasteTypes]); return res.status(201).json({ ok: true, trucker: r.rows[0] }); }
    if (action === 'add_facility') { const name = String(body.name || '').trim(); const type = String(body.facility_type || 'disposal'); if (!name || !['disposal','recycling','composting','transfer'].includes(type)) return res.status(400).json({ error: 'Facility name and type are required.' }); const accepted = Array.isArray(body.accepted_waste_types) && body.accepted_waste_types.length ? body.accepted_waste_types.filter(validWasteType) : ['general']; const r = await db.query(`INSERT INTO disposal_facilities (owner_user_id, name, facility_type, address, accepted_waste_types) VALUES ($1, $2, $3, NULLIF($4, ''), $5) RETURNING id, name, facility_type, address, accepted_waste_types`, [userId, name, type, String(body.address || '').trim(), accepted]); return res.status(201).json({ ok: true, facility: r.rows[0] }); }
    if (action === 'request_job') { const pointId = body.collection_point_id || null; const wasteType = String(body.waste_type || 'general'); const weight = Number(body.estimated_weight_kg); const fee = Number(body.collection_fee || 0); if (!validWasteType(wasteType) || !Number.isFinite(weight) || weight <= 0 || weight > 100000 || !Number.isFinite(fee) || fee < 0) return res.status(400).json({ error: 'Waste type, estimated weight and a valid collection fee are required.' }); if (pointId) { const p = await db.query(`SELECT id FROM collection_points WHERE id = $1 AND market_id = $2 AND active = true`, [pointId, market.id]); if (!p.rows[0]) return res.status(400).json({ error: 'That collection point does not belong to this market.' }); } const r = await db.query(`INSERT INTO waste_jobs (market_id, collection_point_id, waste_type, estimated_weight_kg, collection_fee, requested_by, notes) VALUES ($1, $2, $3, $4, $5, $6, NULLIF($7, '')) RETURNING id, status, waste_type, estimated_weight_kg, collection_fee, requested_at`, [market.id, pointId, wasteType, weight, fee, userId, String(body.notes || '').trim()]); await db.query(`INSERT INTO waste_job_events (job_id, event_type, actor_user_id, note) VALUES ($1, 'requested', $2, $3)`, [r.rows[0].id, userId, 'Collection request created']); return res.status(201).json({ ok: true, job: r.rows[0] }); }
    if (action === 'assign_job') { const jobId = String(body.job_id || ''); const truckerId = String(body.trucker_id || ''); const facilityId = body.facility_id ? String(body.facility_id) : null; const job = await db.query(`SELECT id FROM waste_jobs WHERE id = $1 AND market_id = $2`, [jobId, market.id]); const trucker = await db.query(`SELECT id FROM truckers WHERE id = $1 AND owner_user_id = $2 AND active = true`, [truckerId, userId]); if (!job.rows[0] || !trucker.rows[0]) return res.status(400).json({ error: 'Job or trucker could not be verified.' }); if (facilityId) { const f = await db.query(`SELECT id FROM disposal_facilities WHERE id = $1 AND owner_user_id = $2 AND active = true`, [facilityId, userId]); if (!f.rows[0]) return res.status(400).json({ error: 'Facility could not be verified.' }); } const r = await db.query(`UPDATE waste_jobs SET trucker_id = $1, facility_id = $2, status = 'assigned' WHERE id = $3 AND market_id = $4 RETURNING id, status, trucker_id, facility_id`, [truckerId, facilityId, jobId, market.id]); await db.query(`INSERT INTO waste_job_events (job_id, event_type, actor_user_id, note) VALUES ($1, 'assigned', $2, $3)`, [jobId, userId, 'Trucker assigned']); return res.json({ ok: true, job: r.rows[0] }); }
    if (action === 'update_job') { const jobId = String(body.job_id || ''); const status = String(body.status || ''); if (!validStatus(status)) return res.status(400).json({ error: 'Invalid collection status.' }); const job = await db.query(`SELECT id FROM waste_jobs WHERE id = $1 AND market_id = $2`, [jobId, market.id]); if (!job.rows[0]) return res.status(404).json({ error: 'Waste job not found.' }); const weight = body.collected_weight_kg == null ? null : Number(body.collected_weight_kg); if (weight !== null && (!Number.isFinite(weight) || weight <= 0)) return res.status(400).json({ error: 'Enter a valid collected weight.' }); const r = await db.query(`UPDATE waste_jobs SET status = $1, collected_weight_kg = COALESCE($2, collected_weight_kg), collected_at = CASE WHEN $1 = 'collected' THEN COALESCE(collected_at, now()) ELSE collected_at END, delivered_at = CASE WHEN $1 = 'delivered' THEN COALESCE(delivered_at, now()) ELSE delivered_at END WHERE id = $3 AND market_id = $4 RETURNING id, status, collected_weight_kg, collected_at, delivered_at`, [status, weight, jobId, market.id]); await db.query(`INSERT INTO waste_job_events (job_id, event_type, actor_user_id, latitude, longitude, note) VALUES ($1, $2, $3, $4, $5, $6)`, [jobId, status, userId, body.latitude ?? null, body.longitude ?? null, String(body.note || '').trim() || null]); return res.json({ ok: true, job: r.rows[0] }); }
    return res.status(400).json({ error: 'Unknown waste action.' });
  } catch (error) { console.error('waste operation failed', error); return res.status(500).json({ error: 'We could not complete that waste operation. Please try again.' }); }
}